#服务器配置
server:
  port: 8099

spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名

#swagger公共信息
swagger:
  title: NHIS 接口文档系统
  description: NHIS 接口文档系统
  version: 1.0.0.RELEASE
  license: Powered By NHIS
  license-url: http://www.zebone.cn
  terms-of-service-url: http://www.zebone.cn
  contact:
    name: lijin
    email: lijin77555@gmail.com
    url: https://github.com/S-117-John

#缓存
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#配置日志地址
logging:
  config: classpath:log/logback-${blade.env}-spring.xml


